[package]
name = "csv-macros"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proc-macro2 = "1.0.36"
proc-quote = "0.4.0"
syn = "1.0.84"
csv = "1.1"
phf = "0.10"

[lib]
proc-macro = true
